### ISSUE TITLE
Please always use $(CFLAGS) in compile lines and $(LDFLAGS) in link lines

### ISSUE THREAD

**Issue by yurivict** [mkoeppe/lrslib#3]
Ex. ```-O3``` shouldn't be here: https://github.com/mkoeppe/lrslib/blob/master/makefile#L146

**Comment by mkoeppe** [comment]
This repository is for maintaining the "autoconfiscation" branch, which changes the build system to use autotools. 
I have just deleted the "master" branch, which was the same as "upstream", to make this clearer.
