### ISSUE TITLE
No rule to make target 'redundgmp', needed by 'default'.  Stop.

### ISSUE THREAD

**Issue by yurivict** [mkoeppe/lrslib#4]

**Comment by mkoeppe** [comment]
This repository is for maintaining the "autoconfiscation" branch, which changes the build system to use autotools. Report any issues with the upstream build system to the upstream authors.

I have just deleted the "master" branch, which was the same as "upstream", to make this clearer.

**Comment by yurivict** [comment]
So what is the very latest release?

I used ```070``` and ran into these problems.
Now you deleted some branches, but ```070``` is still shown as the latest release and all the above problems are still there.

**Comment by mkoeppe** [comment]
Upstream (http://cgm.cs.mcgill.ca/~avis/C/lrs.html) has released 070. I have imported it on the `upstream` branch but have not yet updated the `autoconfiscation` branch. Help with this would certainly be welcome.
